### ISSUE TITLE
ETA, Elapsed time and remaining time not working

### ISSUE THREAD

**Issue by simphide** [xZetsubou/ha-threedy-card#10]
Hi, I wanted to report that the following fields are not properly displayed:
![image](https://github.com/xZetsubou/ha-threedy-card/assets/8183517/27a42338-8c25-4951-a0ee-728d4352c9f2)

This are the correct infos:
![image](https://github.com/xZetsubou/ha-threedy-card/assets/8183517/2f95a8ae-9058-4a0d-a711-d129bb277373)

Do you need any more information?

Thank you!

**Comment by xZetsubou** [comment]
It seems it works fine with me, can you post you card config yaml.
Check the entities in OctoPrint integration are working fine and return correct values.

**Comment by simphide** [comment]
The yaml code is as follows: 
```
type: custom:threedy-card
base_entity: sensor.octoprint
printer_type: I3
name: Anycubic
theme: Default
scale: 1
round_time: true
round_temperature: true
temperature_unit: C
use_24hr: true
power_entity: switch.anycubic_kobra_switch_switch
light_entity: light.hue_ambiance_candle_1
always_show: true
monitored:
  - Status
  - Hotend
  - Bed
  - ETA
  - Elapsed
  - Remaining
```

The entities return correct values as well (it is just unknown right now, because the 3d printer is turned off):
<img width="595" alt="image" src="https://github.com/xZetsubou/ha-threedy-card/assets/8183517/88b0979d-1eb8-4d8d-9172-a5848ae1a3d8">

**Comment by xZetsubou** [comment]
Try remove `round_time: true`
Edit:
Disabling `round time` should fix Remaining and Elapsed.  however it seems I made typo in last update and insert incorrect entity for `ETA` for `base_entity` case, so update 2.1.9 should fix `ETA`

**Comment by simphide** [comment]
Here we go!
<img width="506" alt="image" src="https://github.com/xZetsubou/ha-threedy-card/assets/8183517/c8cb8444-8eda-4db9-bf8b-a90228c3480c">
Thank you!
