### ISSUE TITLE
Icon color depending state off printer

### ISSUE THREAD

**Issue by arnoakavdb** [xZetsubou/ha-threedy-card#11]
Is it possible to make the power icon colored depending the state of the switch to know if the printer is powered or not?

**Comment by xZetsubou** [comment]
u mean this one? 

![image](https://github.com/xZetsubou/ha-threedy-card/assets/46300268/7e43bc9c-82e7-48f6-a8c6-2859d11329dc)

**Comment by arnoakavdb** [comment]
Yes exactly

**Comment by xZetsubou** [comment]
Added on [2.1.9.1](https://github.com/xZetsubou/ha-threedy-card/releases/tag/2.1.9.1)

**Comment by arnoakavdb** [comment]
Thank you
