### ISSUE TITLE
multiple printers?

### ISSUE THREAD

**Issue by jonathan-chin** [xZetsubou/ha-threedy-card#8]
I've got 2 printers set up. I can install the default OctoPrint cards just fine but when trying to add them with threedy, I can only get one of them. the other can't seem to connect. any ideas? I suspect it's because the base_entity name is sensor.octoprint_2

**Comment by xZetsubou** [comment]
originally this card made with only 1 octoprint instance in mind i guess, **But** this fork has `custom_sensors` feature you can use it instead of relying  on `base_entity` check [examples](https://github.com/xZetsubou/ha-threedy-card#examples)

**Comment by jonathan-chin** [comment]
thanks! I saw the examples but didn't immediately read it because it didn't say anything about multiple printers. I was eventually able to figure it out!

now, the issue is that I can't get ETA or Remaining to work. I've seen it mentioned a bunch on the other forks; is it fixed? I'm not using MQTT right now, if that matters.

**Comment by xZetsubou** [comment]
Edit: I just tested official octoprint and surprisely it reports times on `UTC ISO 8601` format this probably need to be fixed.

**Comment by xZetsubou** [comment]
Update to [2.1.7](https://github.com/xZetsubou/ha-threedy-card/releases/tag/2.1.7) see if it fixed the issues.
override ETA and Remaining with `sensor.octoprint_estimated_finish_time`

**Comment by jonathan-chin** [comment]
yes, I'm ysing the official octoprint integration. what should I override them with?

**Comment by jonathan-chin** [comment]
hey!!!! I think it works now. this is so cool; thanks!
